[default.probe]
protocol = "Swd"
speed = 20000


[default.flashing]
enabled = true
do_chip_erase = false


[default.reset]
enabled = true
halt_afterwards = false


[default.general]
chip = "RP2040"
log_level = "INFO"
# RP2040 does not support connect_under_reset
connect_under_reset = false


[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "NoBlockTrim", format = "Defmt", show_location = true, show_timestamps = true },
    { channel = 1, mode = "NoBlockTrim", format = "Defmt", show_location = true, show_timestamps = true },
]
down_channels = [{ channel = 0, mode = "NoBlockTrim" }]
timeout = 10000
log_enabled = false
log_path = "./logs"


[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:2345"
