[package]
name = "archon_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "archon_core"
path = "src/lib.rs"
test = false
bench = false


[dependencies.embsys]
git = "https://github.com/syn-chromatic/embsys-rs.git"
rev = "bb167f98ef4c7cda5f6d29f909be38b973d4c37b"
package = "embsys"
features = ["rp2040-probe"]


[dependencies.num]
version = "0.4"
default-features = false