[package]
name = "archon_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "archon_core"
path = "src/lib.rs"
test = false
bench = false


[dependencies.embsys]
workspace = true


[dependencies.num]
workspace = true
