[package]
name = "archon_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "archon_core"
path = "src/lib.rs"
test = false
bench = false


[dependencies.embsys]
git = "https://github.com/syn-chromatic/embsys-rs.git"
rev = "3a78c5c0a961b02a4f9522ceeda84d10d9264490"
package = "embsys"
features = ["rp2040-probe"]


[dependencies.num]
version = "0.4"
default-features = false