[package]
name = "archon_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "archon_core"
path = "src/lib.rs"
test = false
bench = false


[dependencies.embsys]
git = "https://github.com/syn-chromatic/embsys-rs.git"
rev = "9c22e21a45afbe7aa5a4c08c3fa75795b63da34d"
package = "embsys"
features = ["rp2040-probe"]
