[package]
name = "archon-receiver"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "archon-receiver"
test = false
bench = false


[dependencies.archon_core]
path = "../archon-core"


[dependencies.embsys]
git = "https://github.com/syn-chromatic/embsys-rs.git"
rev = "4af01b4899029c0091802074763ea9ca830e5998"
package = "embsys"
features = ["rp2040-probe"]
