[package]
name = "archon-receiver"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "archon-receiver"
test = false
bench = false


[dependencies.archon_core]
workspace = true


[dependencies.embsys]
workspace = true
